version: "3"

services:

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  backend:
    build: ./backend
    ports:
      - "3000:3000"

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
